# Generated by Django 6.0.5 on 2026-05-07 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxogramas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_acesso', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade_de_acessos', models.BigIntegerField(default=0)),
                ('fluxograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxogramas.fluxograma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quantidade_de_acessos', '-ultimo_acesso'],
                'unique_together': {('usuario', 'fluxograma')},
            },
        ),
    ]
