# Generated by Django 6.0.5 on 2026-06-07 14:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('principio_ativo', models.CharField(blank=True, max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DoseReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_mg_por_kg', models.DecimalField(decimal_places=3, help_text='Dose em mg por kg. Ex: 10 mg/kg.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('dose_maxima_mg', models.DecimalField(blank=True, decimal_places=3, help_text='Dose máxima total em mg, se existir.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('intervalo_horas', models.PositiveSmallIntegerField(blank=True, help_text='Intervalo entre doses, em horas.', null=True)),
                ('fonte', models.CharField(blank=True, help_text='Fonte ou protocolo usado para cadastrar a dose.', max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses_referencia', to='calculadora.medicamento')),
            ],
            options={
                'verbose_name': 'Dose de referência',
                'verbose_name_plural': 'Doses de referência',
                'ordering': ['medicamento__nome'],
            },
        ),
        migrations.CreateModel(
            name='ApresentacaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome da apresentação. Ex: suspensão oral, gotas, solução.', max_length=120)),
                ('concentracao_mg_por_ml', models.DecimalField(decimal_places=3, help_text='Concentração em mg/mL. Ex: 200 mg/mL.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('apresentacao', models.CharField(choices=[('ml', 'mL'), ('gotas', 'Gotas')], default='ml', help_text='Formato de saída do cálculo.', max_length=10)),
                ('gotas_por_ml', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Quantidade de gotas por mL. Padrão comum: 20 gotas/mL.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('via_administracao', models.CharField(blank=True, help_text='Ex: oral, intravenosa, intramuscular.', max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='calculadora.medicamento')),
            ],
            options={
                'verbose_name': 'Apresentação do medicamento',
                'verbose_name_plural': 'Apresentações dos medicamentos',
                'ordering': ['medicamento__nome', 'nome'],
            },
        ),
    ]
