# Generated by Django 6.0.5 on 2026-06-08 00:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peso', 'Por peso (dose × peso × fator)'), ('fixa', 'Equivalência fixa (dose × fator)')], max_length=10)),
                ('fator', models.DecimalField(decimal_places=4, help_text='tipo=peso: resultado = dose × peso_kg × fator. tipo=fixa: resultado = dose × fator.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unidade_origem', models.CharField(help_text='Ex: mcg/kg/min, mg', max_length=30)),
                ('unidade_destino', models.CharField(help_text='Ex: mg/dia, mg', max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medicamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_destino', to='calculadora.medicamento')),
                ('medicamento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_origem', to='calculadora.medicamento')),
            ],
            options={
                'verbose_name': 'Conversão de medicamento',
                'verbose_name_plural': 'Conversões de medicamentos',
                'ordering': ['medicamento_origem__nome', 'medicamento_destino__nome'],
            },
        ),
    ]
