# Generated by Django 6.0.5 on 2026-05-23 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('binaria', 'Binária'), ('multipla_escolha', 'Múltipla escolha'), ('numerica', 'Numérica')], default='binaria', max_length=30),
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='casos.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TelaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('caso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas_resultado', to='casos.casoclinico')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
