# Generated by Django 6.0.5 on 2026-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_alter_questao_tipo_opcaoresposta_telaresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='feedback_correto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='feedback_incorreto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
