# Generated by Django 6.0.5 on 2026-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluxograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conteudo', models.JSONField(help_text='Estrutura JSON do fluxo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
