# Generated by Django 6.0.5 on 2026-05-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxogramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('fluxograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='fluxogramas.fluxograma')),
            ],
        ),
        migrations.CreateModel(
            name='PassoRaciocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('descricao', models.TextField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='fluxogramas.casoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('unidade', models.CharField(max_length=50)),
                ('resposta_correta', models.FloatField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='fluxogramas.casoclinico')),
            ],
        ),
    ]
