# Generated by Django 6.0.5 on 2026-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxogramas', '0002_casoclinico_passoraciocinio_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoclinico',
            name='fluxograma',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='caso',
        ),
        migrations.DeleteModel(
            name='PassoRaciocinio',
        ),
        migrations.DeleteModel(
            name='CasoClinico',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
